version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://skilluser:skillpass@db:5432/skilldb
      - SESSION_SECRET=your-session-secret-key
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - lms-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=skilldb
      - POSTGRES_USER=skilluser
      - POSTGRES_PASSWORD=skillpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skilluser -d skilldb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lms-network

volumes:
  postgres_data:

networks:
  lms-network:
    driver: bridge
